-- Get product level, order level and shipping promotion for a store.

SELECT T0.PX_PROMOTION_ID, T0.NAME,T2.CALCODE_ID FROM PX_PROMOTION T0, PX_GROUP T1, CLCDPROMO T2, CALCODE T3
WHERE T0.PX_GROUP_ID=T1.PX_GROUP_ID AND T0.PX_PROMOTION_ID=T2.PX_PROMOTION_ID AND T2.CALCODE_ID=T3.CALCODE_ID
AND T0.STOREENT_ID IN (10951) AND T0.STATUS =1 AND T0.CDREQUIRED=0 AND T0.TYPE=0
AND T0.STARTDATE <= current_timestamp AND T0.ENDDATE >= current_timestamp 
AND T1.GRPNAME IN ('ProductLevelPromotion','OrderLevelPromotion','ShippingPromotion')
AND T1.STOREENT_ID IN (10951) AND T3.DISPLAYLEVEL=1;

SELECT T0.PX_PROMOTION_ID, T0.NAME FROM PX_PROMOTION T0, PX_GROUP T1
WHERE T0.PX_GROUP_ID=T1.PX_GROUP_ID AND T0.STOREENT_ID IN (10951)
AND T0.STATUS =1 AND T0.CDREQUIRED=0 AND T0.TYPE=0 AND
T0.STARTDATE <= current_timestamp AND T0.ENDDATE >= current_timestamp
AND T1.GRPNAME IN ('ProductLevelPromotion','OrderLevelPromotion','ShippingPromotion')
AND T1.STOREENT_ID IN (10951) AND NOT EXISTS(SELECT 1 FROM CLCDPROMO T2, CATENCALCD T3 
WHERE T2.CALCODE_ID=T3.CALCODE_ID AND T0.PX_PROMOTION_ID=T2.PX_PROMOTION_ID
UNION ALL SELECT 1 FROM CLCDPROMO T4, CATGPCALCD T5 
WHERE T4.CALCODE_ID=T5.CALCODE_ID AND T0.PX_PROMOTION_ID=T4.PX_PROMOTION_ID);
