connect '..\db\mall;create=true'; 

CREATE TABLE XMYTable (
	MY_SYSTEM_ID BIGINT NOT NULL,
	MY_ID BIGINT NOT NULL,
	firstName	VARCHAR(254),
	lastName	VARCHAR(254)
);

ALTER TABLE XMYTable
       ADD PRIMARY KEY (MY_SYSTEM_ID);
       
CREATE UNIQUE INDEX I0000_XMYTable ON XMYTable	
(
       MY_ID                        ASC
);

       
INSERT INTO KEYS (KEYS_ID, TABLENAME, COLUMNNAME, COUNTER, PREFETCHSIZE, LOWERBOUND, UPPERBOUND, OPTCOUNTER)
VALUES ((SELECT MAX(KEYS_ID) + 1 FROM KEYS), 'xmytable', 'MY_SYSTEM_ID', 0000, 1, 1, 999999, 1);

commit;


